version: '3'

services:

  postgres:
    build: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"

  auth:
    depends_on:
      - postgres
    build:
      context: ../auth
      dockerfile: ../omo.earth/auth/Dockerfile
    env_file:
      - .env
    environment:
      # Sucks: The hash is a comment in .env-files, so this variable must be set
      # inside of this file.
      - AUTH_APP_REDIRECT=https://alpha.omo.earth/#!/sign-in/onetime
    ports:
      - "80"

  identity:
    depends_on:
      - postgres
      - auth
    build:
      context: ../
      dockerfile: omo.earth/identity/Dockerfile
    env_file:
      - .env
    ports:
      - "80"

  proxy:
    depends_on:
      - auth
      - identity
    build:
      context: proxy
      dockerfile: Dockerfile
      args:
        - PROXY_PROTOCOL=${PROXY_PROTOCOL}
        - PROXY_DOMAIN=${PROXY_DOMAIN}
        - PROXY_PORT=${PROXY_PORT}
        - PROXY_EXTERN_DOMAIN=${PROXY_EXTERN_DOMAIN}
        - PROXY_EXTERN_PORT=${PROXY_EXTERN_PORT}
        - PROXY_SERVICE_AUTH_PATH=${PROXY_SERVICE_AUTH_PATH}
        - PROXY_SERVICE_IDENTITY_PATH=${PROXY_SERVICE_IDENTITY_PATH}
        - APP_PROTOCOL=${APP_PROTOCOL}
        - APP_DOMAIN=${APP_DOMAIN}
        - APP_PORT=${APP_PORT}
        - AUTH_PROTOCOL=${AUTH_PROTOCOL}
        - AUTH_DOMAIN=${AUTH_DOMAIN}
        - AUTH_PORT=${AUTH_PORT}
        - IDENTITY_PROTOCOL=${IDENTITY_PROTOCOL}
        - IDENTITY_DOMAIN=${IDENTITY_DOMAIN}
        - IDENTITY_PORT=${IDENTITY_PORT}
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/alpha.omo.earth:/etc/letsencrypt/live/alpha.omo.earth
