version: '3'

services:

  postgres:
    build: postgres
    env_file:
      - .env
    ports:
      - "5432"

  auth:
    depends_on:
      - postgres
    build:
      context: ../auth
      dockerfile: ../omo.local/auth/Dockerfile
    env_file:
      - .env
    ports:
      - "80"

  app:
    depends_on:
      - postgres
      - auth
    build:
      context: ../app
      dockerfile: ../omo.local/app/Dockerfile
    env_file:
      - .env
    ports:
      - "80"

  static:
    build: static
    ports:
      - "80"

  proxy:
    depends_on:
      - static
      - auth
      - app
    build: proxy
    env_file:
      - .env
    ports:
      - "8080:80"
