version: '3'

services:

  postgres:
    build: postgres
    env_file:
      - .env
    ports:
      - "5432"

  omo-auth:
    depends_on:
      - postgres
    build:
      context: ../auth
      dockerfile: ../omo.local/omo-auth/Dockerfile
    env_file:
      - .env
    ports:
      - "80"

  static:
    build: static
    ports:
      - "80"

  proxy:
    depends_on:
      - static
      - omo-auth
    build: proxy
    env_file:
      - .env
    ports:
      - "8080:80"
