version: '3'

services:

  postgres:
    build: postgres
    env_file:
      - .env
    ports:
      - "5432"

  auth:
    depends_on:
      - postgres
    build:
      context: ../auth
      dockerfile: ../omo.local/auth/Dockerfile
    env_file:
      - .env
    environment:
      # Sucks: The hash is a comment in .env-files, so this variable must be set
      # inside of this file.
      - APP_ONE_TIME_TOKEN_SIGNIN_URL=http://localhost:5000/#!/sign-in/onetime
    ports:
      - "80"

  keystore:
    depends_on:
      - postgres
    build:
      context: ../
      dockerfile: omo.local/keyStore/Dockerfile
    env_file:
      - .env
    ports:
      - "80"

  app:
    depends_on:
      - postgres
      - auth
      - keystore
    build:
      context: ../app
      dockerfile: ../omo.local/app/Dockerfile
    env_file:
      - .env
    ports:
      - "80"

  static:
    build: static
    ports:
      - "80"

  proxy:
    depends_on:
      - static
      - auth
      - app
    build: proxy
    env_file:
      - .env
    ports:
      - "8080:80"
